### ISSUE TITLE
[ Random Suggestions ]

### ISSUE THREAD

**Issue by SPF420** [thomasgoldstein/epicedit#21] opened 2024-10-17 22:57 UTC
Not fully sure if any of these could be implemented into the game but having slightly larger maps and the ability to have more items on the ground would be nice.

**Comment by thomasgoldstein** [comment] 2024-10-18 18:26
Long story short, I don't know how to do any of that, but anyone is free to try. :)

More items on the ground is a hard limitation of the SNES, as far as I know. Back in the days, I asked smkdan if he could do it, and he did, and he confirmed the game would slow down a lot. Those limits were put in place for a reason.

Larger maps might be technically possible, I don't know, but that sounds pretty ambitious, and sounds like it'd require recoding most of the game.

I'm going to close this issue, because although these requests may not be technically impossible, they're very unlikely to ever happen.

**Closed as completed by thomasgoldstein** 2024-10-18 18:26 UTC
